services:
  - type: web
    name: james-ai-voicebot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    branch: main
    envVars:
      - key: GEMINI_API_KEY
        sync: false
